In [1]:
import sys
import numpy as np

#Basic numpy arrays

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([0,.5,1,1.5,2])

In [ ]:
a[0]

1

In [ ]:
a[0], a[2]

(1, 3)

In [ ]:
a[:4]

array([1, 2, 3, 4])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
a[1::3]

array([2])

In [ ]:
a[1::4]

array([2])

In [ ]:
a[::3]

array([1, 4])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[[1, -1]]

array([0.5, 2. ])

In [ ]:
b[0], b[-1], a[2]

(0.0, 2.0, 3)

#Array types

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1,2,3,4], dtype=np.float16)

array([1., 2., 3., 4.], dtype=float16)

In [ ]:
np.array([1.,2.,3.,4.], dtype=int)


array([1, 2, 3, 4])

In [ ]:
c = np.array(['a','b','c','d'])

In [ ]:
c.dtype

dtype('<U1')

#Dimensions and shape

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [1,2,3]
    ],
    [
        [4,5,6],
        [7,8,9]
    ]
])

In [ ]:
B

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [ ]:
B.shape

(3, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

18

#Indexing and slicing matrices

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
A[1][0]

4

In [ ]:
A[2][1]

8

In [ ]:
A[1,0]

4

In [ ]:
A[2,1]

8

In [ ]:
A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
A[2] = 22

In [ ]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 22, 22]])

In [ ]:
A[2,1] = 11

In [ ]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 11, 22]])

#Summary statistics

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 11, 22]])

In [ ]:
A.sum()

76

In [ ]:
A.mean()

8.444444444444445

In [ ]:
A.std()

7.7332056183579185

In [ ]:
A.var()

59.802469135802475

In [ ]:
A.sum(axis=0)

array([27, 18, 31])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 55])

In [ ]:
A.mean(axis=0)

array([ 9.        ,  6.        , 10.33333333])

In [ ]:
A.mean(axis=1)

array([ 2.        ,  5.        , 18.33333333])

In [ ]:
A.std(axis=0)

array([9.2736185 , 3.74165739, 8.33999734])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 5.18544973])

In [ ]:
A.var(axis=0)

array([86.        , 14.        , 69.55555556])

In [ ]:
A.var(axis=1)

array([ 0.66666667,  0.66666667, 26.88888889])

#Broadcasting and vectorized operations

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a + 10

array([10, 11, 12, 13])

In [5]:
a * 10

array([ 0, 10, 20, 30])

In [6]:
a

array([0, 1, 2, 3])

In [7]:
a += 100

In [8]:
a

array([100, 101, 102, 103])

In [9]:
l = [0,1,2,3]

In [10]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [11]:
a -= 100

In [12]:
b = np.array([10,10,10,10])

In [13]:
a + b

array([10, 11, 12, 13])

In [14]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays

In [15]:
a = np.arange(4)

In [16]:
a

array([0, 1, 2, 3])

In [18]:
a[[0,-1]]

array([0, 3])

In [20]:
a[[True, False, False, True]]

array([0, 3])

In [21]:
a[a>=2]

array([2, 3])

In [22]:
a.mean()

1.5

In [23]:
a[a>a.mean()]

array([2, 3])

In [24]:
a[~(a>a.mean())]

array([0, 1])

In [26]:
a[(a<=2) & (a%2==0) ]

array([0, 2])

In [27]:
A = np.random.randint(100, size=(3,3))

In [28]:
A

array([[77, 86, 16],
       [40, 81, 88],
       [98, 16, 16]])

In [29]:
A>30

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [30]:
A[A>30]

array([77, 86, 40, 81, 88, 98])